# Generated by Django 3.0.3 on 2020-04-18 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing_Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemTitle', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('county', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='house_preview/')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
