# Generated by Django 2.0.4 on 2020-03-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20200331_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_database',
            name='county',
            field=models.CharField(max_length=30),
        ),
    ]
