# Generated by Django 2.0.4 on 2020-03-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20200331_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_database',
            name='phoneNumber',
            field=models.CharField(max_length=10),
        ),
    ]
