# Generated by Django 2.2 on 2020-04-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20200420_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing_database',
            old_name='itemTitle',
            new_name='item_category',
        ),
        migrations.RenameField(
            model_name='listing_database',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='listing_database',
            name='item_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
