# Generated by Django 2.2 on 2020-04-20 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_listing_database_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing_database',
            name='method',
        ),
    ]
