# Generated by Django 2.0.4 on 2020-03-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20200206_1105'),
        ('projects', '0008_auto_20200205_1901'),
    ]

    operations = [
    ]
