# Generated by Django 2.0.4 on 2020-03-31 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20200327_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing_database',
            old_name='bathRoom',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='listing_database',
            old_name='address',
            new_name='itemTitle',
        ),
        migrations.RenameField(
            model_name='listing_database',
            old_name='bedRooms',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='listing_database',
            old_name='rentPrice',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='listing_database',
            name='tenantCondtions',
        ),
        migrations.AlterField(
            model_name='listing_database',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
