# Generated by Django 2.0.4 on 2020-04-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20200331_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_database',
            name='phoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
