# Generated by Django 3.0.3 on 2020-04-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20200401_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_database',
            name='image',
            field=models.ImageField(upload_to='listing_pics/'),
        ),
    ]
