# Generated by Django 2.2 on 2020-04-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20200421_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_database',
            name='method',
            field=models.CharField(default=1, max_length=15),
        ),
    ]
